# Generated by Django 6.0.7 on 2026-07-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_note_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
